<section class="clearfix features loaded" id="features">
   <h1>Features</h1>
   <div class="red-line"></div>
   <ul class="features-list clearfix">
      <li class="clearfix"><span class="img"><img onerror="this.setAttribute('src', '//dev.wooter.co/static/default/img/default-icon-feature.png')" src="//dev.wooter.co/static/default/promotionv2/icons/whistle.png" alt=""></span> <span class="txt">Referees</span></li>
      <li class="clearfix"><span class="img"><img onerror="this.setAttribute('src', '//dev.wooter.co/static/default/img/default-icon-feature.png')" src="//dev.wooter.co/static/default/promotionv2/icons/jersey.png" alt=""></span> <span class="txt">Jerseys</span></li>
      <li class="clearfix"><span class="img"><img onerror="this.setAttribute('src', '//dev.wooter.co/static/default/img/default-icon-feature.png')" src="//dev.wooter.co/static/default/promotionv2/icons/playoffs.png" alt=""></span> <span class="txt">Playoffs</span></li>
      <li class="clearfix"><span class="img"><img onerror="this.setAttribute('src', '//dev.wooter.co/static/default/img/default-icon-feature.png')" src="//dev.wooter.co/static/default/promotionv2/icons/star.png" alt=""></span> <span class="txt">All-Star Game</span></li>
      <li class="clearfix"><span class="img"><img onerror="this.setAttribute('src', '//dev.wooter.co/static/default/img/default-icon-feature.png')" src="//dev.wooter.co/static/default/promotionv2/icons/trophy.png" alt=""></span> <span class="txt">Trophies and Awards</span></li>
      <li class="clearfix"><span class="img"><img onerror="this.setAttribute('src', '//dev.wooter.co/static/default/img/default-icon-feature.png')" src="//dev.wooter.co/static/default/promotionv2/icons/tracking.png" alt=""></span> <span class="txt">Stat Tracking</span></li>
      <li class="clearfix"><span class="img"><img onerror="this.setAttribute('src', '//dev.wooter.co/static/default/img/default-icon-feature.png')" src="//dev.wooter.co/static/default/promotionv2/icons/hype_man.png" alt=""></span> <span class="txt">Commentators/Hype Man/DJ</span></li>
      <li class="clearfix"><span class="img"><img onerror="this.setAttribute('src', '//dev.wooter.co/static/default/img/default-icon-feature.png')" src="//dev.wooter.co/static/default/promotionv2/icons/press.png" alt=""></span> <span class="txt">Press Attention</span></li>
      <li class="clearfix"><span class="img"><img onerror="this.setAttribute('src', '//dev.wooter.co/static/default/img/default-icon-feature.png')" src="//dev.wooter.co/static/default/promotionv2/icons/scout.png" alt=""></span> <span class="txt">Scouts or Evaluators</span></li>
      <li class="clearfix"><span class="img"><img onerror="this.setAttribute('src', '//dev.wooter.co/static/default/img/default-icon-feature.png')" src="//dev.wooter.co/static/default/promotionv2/icons/flim.png" alt=""></span> <span class="txt">Film Recording/Analysis</span></li>
      <li class="clearfix"><span class="img"><img onerror="this.setAttribute('src', '//dev.wooter.co/static/default/img/default-icon-feature.png')" src="//dev.wooter.co/static/default/promotionv2/icons/equipment.png" alt=""></span> <span class="txt">Equipment</span></li>
      <li class="clearfix"><span class="img"><img onerror="this.setAttribute('src', '//dev.wooter.co/static/default/img/default-icon-feature.png')" src="//dev.wooter.co/static/default/promotionv2/icons/prize.png" alt=""></span> <span class="txt">Prizes</span></li>
      <li class="clearfix"><span class="img"><img onerror="this.setAttribute('src', '//dev.wooter.co/static/default/img/default-icon-feature.png')" src="//dev.wooter.co/static/default/promotionv2/icons/contest.png" alt=""></span> <span class="txt">Contests</span></li>
      <li class="clearfix"><span class="img"><img onerror="this.setAttribute('src', '//dev.wooter.co/static/default/img/default-icon-feature.png')" src="//dev.wooter.co/static/default/promotionv2/icons/social.png" alt=""></span> <span class="txt">Social Gatherings</span></li>
      <li class="clearfix"><span class="img"><img onerror="this.setAttribute('src', '//dev.wooter.co/static/default/img/default-icon-feature.png')" src="//dev.wooter.co/static/default/promotionv2/icons/rules.png" alt=""></span> <span class="txt">Modified Rules</span></li>
      <li class="clearfix"><span class="img"><img onerror="this.setAttribute('src', '//dev.wooter.co/static/default/img/default-icon-feature.png')" src="//dev.wooter.co/static/default/promotionv2/icons/coach.png" alt=""></span> <span class="txt">Professional/Certified Coaches</span></li>
      <li class="clearfix"><span class="img"><img onerror="this.setAttribute('src', '//dev.wooter.co/static/default/img/default-icon-feature.png')" src="//dev.wooter.co/static/default/promotionv2/icons/venue.png" alt=""></span> <span class="txt">Premier Venue</span></li>
      <li class="clearfix"><span class="img"><img onerror="this.setAttribute('src', '//dev.wooter.co/static/default/img/default-icon-feature.png')" src="//dev.wooter.co/static/default/promotionv2/icons/ped.png" alt=""></span> <span class="txt">PED Testing</span></li>
      <li class="clearfix"><span class="img"><img onerror="this.setAttribute('src', '//dev.wooter.co/static/default/img/default-icon-feature.png')" src="//dev.wooter.co/static/default/promotionv2/icons/tournaments.png" alt=""></span> <span class="txt">Tournaments</span></li>
   </ul>
</section>
